anonymous-forum-csharp/Controllers/CommentController.cs
using anonymous_forum_csharp.Data.Repository.IRepository;
using anonymous_forum_csharp.Helpers;
using anonymous_forum_csharp.Models;
using anonymous_forum_csharp.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace anonymous_forum_csharp.Controllers
{
	public class CommentController : Controller
	{
		private readonly ICommentRepository _commentRepository;
		private readonly IPostRepository _postRepository;

		public CommentController(ICommentRepository commentRepository, IPostRepository postRepository)
		{
			_commentRepository = commentRepository;
			_postRepository = postRepository;
		}
		public IActionResult Index(int id)
		{
			var comments = _commentRepository.GetByCondition(x => x.PostId == id);
			var post = _postRepository.GetByCondition(x => x.Id == id);
			
			var viewModel = CreateViewModel(comments, post);

			return View(viewModel);
		}

		private static CommentViewModel CreateViewModel(IQueryable<CommentModel> comments, IQueryable<PostModel> post)
		{
			var viewModel = new CommentViewModel
			{
				CommentList = comments.Select(u => new CommentModel { Id = u.Id, Text = u.Text, PostId = u.PostId }).ToList(),
				Post = post.Select(u => new PostModel { Id = u.Id, Text = u.Text, Title = u.Title }).FirstOrDefault(),
				AddComment = new AddCommentViewModel()
			};
			return viewModel;
		}
		public IActionResult CommentPostBox()
		{
			AddCommentViewModel viewModel = new();
			return View(viewModel);
		}

		[HttpPost]
		public IActionResult CommentPostBox(AddCommentViewModel viewModel, int id)
		{
			Console.WriteLine($"id: {id}, text: {viewModel.Text}");
			string? ip = Helper.GetIp(HttpContext);
			var comment = new CommentModel
			{
				Text = viewModel.Text,
				IpAdress = ip,
				PostId = id
			};
			_commentRepository.Create(comment);
			_commentRepository.Save();

			return RedirectToAction("Index", new { id = id });
		}
	}
}

anonymous-forum-csharp/Controllers/ThreadController.cs
using anonymous_forum_csharp.Data.Repository.IRepository;
using anonymous_forum_csharp.Helpers;
using anonymous_forum_csharp.Models;
using anonymous_forum_csharp.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace anonymous_forum_csharp.Controllers
{
	public class ThreadController : Controller
	{
		private readonly IPostRepository _postRepository;
		private readonly ITopicRepository _topicRepository;

		public ThreadController(IPostRepository postRepository, ITopicRepository topicRepository)
		{
			_postRepository = postRepository;
			_topicRepository = topicRepository;
		}

		[HttpGet]
		public IActionResult Index(int id)
		{
			var posts = _postRepository.GetByCondition(x => x.TopicId == id);
			var thread = _topicRepository.GetByCondition(x => x.Id == id);
			if (!posts.Any())
			{
				// Handle error
			}

			var viewModel = CreateViewModel(posts, thread);


			string? ip = Helper.GetIp(HttpContext);
			Console.WriteLine(ip);
			return View(viewModel);
		}

		public IActionResult ThreadPostBox()
		{
			ThreadCreateViewModel viewModel = new();
			return View(viewModel);
		}

		[HttpPost]
		public IActionResult ThreadPostBox(ThreadCreateViewModel viewModel, int id)
		{
			Console.WriteLine($"id: {id}, text: {viewModel.Text}, title: {viewModel.Title}");
			string? ip = Helper.GetIp(HttpContext);
			var post = new PostModel
			{
				Title = viewModel.Title,
				Text = viewModel.Text,
				IpAdress = ip,
				TopicId = id
			};
			_postRepository.Create(post);
			_postRepository.Save();



			return RedirectToAction("Index", new { id = id });
		}

		private static ThreadIndexViewModel CreateViewModel(IQueryable<PostModel> posts, IQueryable<TopicModel> topic)
		{
			var viewModel = new ThreadIndexViewModel
			{
				PostList = posts.Select(u => new PostModel { Id = u.Id, Title = u.Title, Text = u.Text, TopicId = u.TopicId }).ToList(),
                Topic = topic.Select(u => new TopicModel { Id = u.Id, Name = u.Name }).FirstOrDefault()
            };
			return viewModel;
		}
	}
}

anonymous-forum-csharp/Views/Thread/Index.cshtml
@using anonymous_forum_csharp.Models.ViewModels
@using anonymous_forum_csharp.Models
@model ThreadIndexViewModel

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>@Model.Topic.Name</h1>

<div class="text-center">
        @foreach (var item in Model.PostList)
        {
        <a href="@Url.Action("Index", "Comment", new { Id = item.Id})">
            <div class="post-box">
            <h4>@item.Title</h4>
            <p>@item.Text</p>
            </div>
        </a>
        }
</div>
@* @using (Html.BeginForm("Index", "Thread"))
{
    @Html.LabelFor(m => m.Post.Title)
    @Html.EditorFor(m => m.Post.Text)
    <input type="submit" value="Create" />
} *@

@await Html.PartialAsync("ThreadPostBox", Model.ThreadCreate)

anonymous-forum-csharp/Views/Thread/ThreadPostBox.cshtml
@using anonymous_forum_csharp.Models.ViewModels
@model ThreadCreateViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}



@using (Html.BeginForm("ThreadPostBox", "Thread", new { Id = ViewContext.RouteData.Values["id"] }, FormMethod.Post))
{
    <div class="input-form">
    @Html.ValidationSummary()

    @Html.LabelFor(m => m.Title)
    @Html.EditorFor(m => m.Title)
    @Html.ValidationMessageFor(m => m.Title)

    @Html.LabelFor(m => m.Text)
    @Html.EditorFor(m => m.Text)
    @Html.ValidationMessageFor(m => m.Text)
        <input class="button" type="submit" value="Create" />
    </div>
    
}